name: ci

on:
  push:
    branches-ignore: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-lint:
    name: Check Code (Lint & Build)
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository
        uses: actions/checkout@v6

      - name: Setup Project
        uses: ./.github/actions/setup-project

      - name: Run Linter
        run: pnpm run lint

      - name: Run Type-Check
        run: pnpm run type-check

      - name: Run Tests
        run: pnpm run test --passWithNoTests

      - name: Run Build
        run: pnpm run build
        env:
          DATABASE_URL: 'postgres://mock:mock@localhost:5432/mock'
          NEXT_PUBLIC_APP_NAME: 'Ai Smart Dictionary'
          NEXT_PUBLIC_APP_DESCRIPTION: 'Ai Smart Dictionary'
